## called to init crops farm for player

##add to list
data modify storage lc:user crops prepend value {}
data modify storage lc:user crops[0].UUID set from entity @s UUID
data modify storage lc:user crops[0].page append value {Slot:2b,id:"minecraft:flower_pot",Count:1b,tag:{menu_ui:1,crops_menu:1,crops_slot:1,unlocked:1,unlock_cost:25,growth:0,display:{Name:'{"text":"空的蔬果架","color":"green","italic":false}',Lore:['{"text":"将背包内的种子放到这里播种","color":"dark_green","italic":false}']}}}
data modify storage lc:user crops[0].page append value {Slot:3b,id:"minecraft:flower_pot",Count:1b,tag:{menu_ui:1,crops_menu:1,crops_slot:2,unlocked:1,unlock_cost:25,growth:0,display:{Name:'{"text":"空的蔬果架","color":"green","italic":false}',Lore:['{"text":"将背包内的种子放到这里播种","color":"dark_green","italic":false}']}}}
data modify storage lc:user crops[0].page append value {Slot:4b,id:"minecraft:flower_pot",Count:1b,tag:{menu_ui:1,crops_menu:1,crops_slot:3,unlocked:1,unlock_cost:25,growth:0,display:{Name:'{"text":"空的蔬果架","color":"green","italic":false}',Lore:['{"text":"将背包内的种子放到这里播种","color":"dark_green","italic":false}']}}}
data modify storage lc:user crops[0].page append value {Slot:5b,id:"minecraft:flower_pot",Count:1b,tag:{menu_ui:1,crops_menu:1,crops_slot:4,unlocked:1,unlock_cost:25,growth:0,display:{Name:'{"text":"空的蔬果架","color":"green","italic":false}',Lore:['{"text":"将背包内的种子放到这里播种","color":"dark_green","italic":false}']}}}
data modify storage lc:user crops[0].page append value {Slot:6b,id:"minecraft:flower_pot",Count:1b,tag:{menu_ui:1,crops_menu:1,crops_slot:5,unlocked:1,unlock_cost:25,growth:0,display:{Name:'{"text":"空的蔬果架","color":"green","italic":false}',Lore:['{"text":"将背包内的种子放到这里播种","color":"dark_green","italic":false}']}}}
data modify storage lc:user crops[0].page append value {Slot:11b,id:"minecraft:structure_void",Count:1b,tag:{menu_ui:1,crops_menu:1,crops_slot:6,unlock_cost:25,growth:0,display:{Name:'{"text":"未解锁的蔬果架","color":"dark_aqua","italic":false}',Lore:['{"text":"点击解锁栏位","color":"gold","italic":false}','[{"text":"花费： ","color":"white","italic":false},{"text":"25","color":"yellow","italic":false}]']}}}
data modify storage lc:user crops[0].page append value {Slot:12b,id:"minecraft:structure_void",Count:1b,tag:{menu_ui:1,crops_menu:1,crops_slot:7,unlock_cost:25,growth:0,display:{Name:'{"text":"未解锁的蔬果架","color":"dark_aqua","italic":false}',Lore:['{"text":"点击解锁栏位","color":"gold","italic":false}','[{"text":"花费： ","color":"white","italic":false},{"text":"25","color":"yellow","italic":false}]']}}}
data modify storage lc:user crops[0].page append value {Slot:13b,id:"minecraft:structure_void",Count:1b,tag:{menu_ui:1,crops_menu:1,crops_slot:8,unlock_cost:25,growth:0,display:{Name:'{"text":"未解锁的蔬果架","color":"dark_aqua","italic":false}',Lore:['{"text":"点击解锁栏位","color":"gold","italic":false}','[{"text":"花费： ","color":"white","italic":false},{"text":"25","color":"yellow","italic":false}]']}}}
data modify storage lc:user crops[0].page append value {Slot:14b,id:"minecraft:structure_void",Count:1b,tag:{menu_ui:1,crops_menu:1,crops_slot:9,unlock_cost:25,growth:0,display:{Name:'{"text":"未解锁的蔬果架","color":"dark_aqua","italic":false}',Lore:['{"text":"点击解锁栏位","color":"gold","italic":false}','[{"text":"花费： ","color":"white","italic":false},{"text":"25","color":"yellow","italic":false}]']}}}
data modify storage lc:user crops[0].page append value {Slot:15b,id:"minecraft:structure_void",Count:1b,tag:{menu_ui:1,crops_menu:1,crops_slot:10,unlock_cost:25,growth:0,display:{Name:'{"text":"未解锁的蔬果架","color":"dark_aqua","italic":false}',Lore:['{"text":"点击解锁栏位","color":"gold","italic":false}','[{"text":"花费： ","color":"white","italic":false},{"text":"25","color":"yellow","italic":false}]']}}}
data modify storage lc:user crops[0].page append value {Slot:20b,id:"minecraft:structure_void",Count:1b,tag:{menu_ui:1,crops_menu:1,crops_slot:11,unlock_cost:50,growth:0,display:{Name:'{"text":"未解锁的蔬果架","color":"dark_aqua","italic":false}',Lore:['{"text":"点击解锁栏位","color":"gold","italic":false}','[{"text":"花费： ","color":"white","italic":false},{"text":"50","color":"yellow","italic":false}]']}}}
data modify storage lc:user crops[0].page append value {Slot:21b,id:"minecraft:structure_void",Count:1b,tag:{menu_ui:1,crops_menu:1,crops_slot:12,unlock_cost:50,growth:0,display:{Name:'{"text":"未解锁的蔬果架","color":"dark_aqua","italic":false}',Lore:['{"text":"点击解锁栏位","color":"gold","italic":false}','[{"text":"花费： ","color":"white","italic":false},{"text":"50","color":"yellow","italic":false}]']}}}
data modify storage lc:user crops[0].page append value {Slot:22b,id:"minecraft:structure_void",Count:1b,tag:{menu_ui:1,crops_menu:1,crops_slot:13,unlock_cost:50,growth:0,display:{Name:'{"text":"未解锁的蔬果架","color":"dark_aqua","italic":false}',Lore:['{"text":"点击解锁栏位","color":"gold","italic":false}','[{"text":"花费： ","color":"white","italic":false},{"text":"50","color":"yellow","italic":false}]']}}}
data modify storage lc:user crops[0].page append value {Slot:23b,id:"minecraft:structure_void",Count:1b,tag:{menu_ui:1,crops_menu:1,crops_slot:14,unlock_cost:100,growth:0,display:{Name:'{"text":"未解锁的蔬果架","color":"dark_aqua","italic":false}',Lore:['{"text":"点击解锁栏位","color":"gold","italic":false}','[{"text":"花费： ","color":"white","italic":false},{"text":"100","color":"yellow","italic":false}]']}}}
data modify storage lc:user crops[0].page append value {Slot:24b,id:"minecraft:structure_void",Count:1b,tag:{menu_ui:1,crops_menu:1,crops_slot:15,unlock_cost:100,growth:0,display:{Name:'{"text":"未解锁的蔬果架","color":"dark_aqua","italic":false}',Lore:['{"text":"点击解锁栏位","color":"gold","italic":false}','[{"text":"花费： ","color":"white","italic":false},{"text":"100","color":"yellow","italic":false}]']}}}
data modify storage lc:user crops[0].page append value {Slot:26b,id:"minecraft:dark_oak_sign",Count:1b,tag:{menu_ui:1,last_open:0,crops_slot:16,display:{Name:'{"text":"禅 花 园","color":"dark_aqua","italic":false}'}}}